config/routes.rb
Rails.application.routes.draw do

  post "likes/:post_id/create" => "likes#create"
  post "likes/:post_id/destroy" => "likes#destroy"

  post "users/:id/update" => "users#update"
  get "users/:id/edit" => "users#edit"
  post "users/create" => "users#create"
  get "signup" => "users#new"
  get "users/index" => "users#index"
  get "users/:id" => "users#show"
  post "login" => "users#login"
  post "logout" => "users#logout"
  get "login" => "users#login_form"
  get "users/:id/likes" => "users#likes"
  get "users/:id/message" => "users#message"

  get "posts/index" => "posts#index"
  get "posts/new" => "posts#new"
  get "posts/:id" =>"posts#show"
  post "posts/create" => "posts#create"
  get "posts/:id/edit" => "posts#edit"
  post "posts/:id/update" => "posts#update"
  post "posts/:id/destroy" => "posts#destroy"
  
  get "category/select_category_index" => "category#select_category_index"
  get "category/select_category_index/:id" => "posts#show"

  get "/" => "home#top"
  get "about" => "home#about"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts
    has_many :users

    def posts
        return Post.where(user_id: self.id)
    end

    def users
        return User.find_by(id: self.user_id)
    end

end

app/models/like.rb
class Like < ApplicationRecord
    validates :user_id, {presence:true}
    validates :post_id, {presence:true}
end

app/models/post.rb
class Post < ApplicationRecord
    validates :content, {presence: true, length: {maximum: 140}}
    validates :user_id, {presence: true}
    
    belongs_to :category
    belongs_to :user, class_name: "User"
    belongs_to :send_user, class_name: "User"

    def user
        return User.find_by(id: self.user_id)
    end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates:name,{presence:true}
  validates:email,{presence:true, uniqueness:true}
  validates :password, presence: true, on: :create
  validates :introduction, presence: false, length: { maximum: 50 }

  has_many :posts, dependent: :destroy
  

  def posts
    return Post.where(user_id: self.id)
  end

  def categories
    return Category.where(category_id: self.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  before_action:set_current_user
  
  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end

  def authenticate_user
    if  @current_user == nil
      flash[:notice] = "ログインが必要です"
      redirect_to("/login")
    end
  end

  def forbid_login_user
    if @current_user
      flash[:notice] = "すでにログインしています"
      redirect_to("/posts/index")
    end
  end

end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  def select_category_index
    @select_category_index1 = Post.where(category_id: 1)
    @select_category_index2 = Post.where(category_id: 2)
    @select_category_index3 = Post.where(category_id: 3)
    @select_category_index4 = Post.where(category_id: 4)

    @post = Post.find_by(id: params[:id])
    @user = User.find_by(id: params[:id])
    
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :forbid_login_user, {only: [:top]}
  
  def top
  end

  def users_show
    @user = @post.user
    @posts = @user.posts
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user
    
    def create
        @like=Like.new(user_id: @current_user.id, post_id: params[:post_id])
        @like.save
        redirect_to("/posts/#{params[:post_id]}")
    end

    def destroy
        @like=Like.find_by(user_id: @current_user.id, post_id: params[:post_id])
        @like.destroy
        redirect_to("/posts/#{params[:post_id]}")
    end
    
  end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action:authenticate_user
  before_action :ensure_correct_user, {only: [:edit, :update, :destroy]}

  def ensure_correct_user
    @post = Post.find_by(id: params[:id])
    if @post.user_id != @current_user.id
      flash[:notice]="権限がありません"
      redirect_to("/posts/index")
    end
  end
  
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def show
    @post = Post.find_by(id: params[:id])
    @user = User.find_by(id: @post.user_id)
    @likes_count = Like.where(post_id: @post.user_id).count

    @select_category_index1 = Post.where(category_id: 1)
    @select_category_index2 = Post.where(category_id: 2)
    @select_category_index3 = Post.where(category_id: 3)
    @select_category_index4 = Post.where(category_id: 4)
  end

  def new
    @post = Post.new
  end

  def create
    @post=Post.new(post_params)
    if @post.save!
      flash[:notice] = "投稿を作成しました"
      redirect_to("/posts/index")
    else
      render("posts/new")
    end  
  end

  def update
    @post = Post.find_by(id: params[:id])
    @post.content = params[:content]
    if @post.save
      flash[:notice] = "投稿を編集しました"
      redirect_to("/posts/index")
    else
      render("posts/edit")
    end
  end
  
  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    flash[:notice] = "投稿を削除しました"
    redirect_to("/posts/index")
  end

  private

  def post_params
    params.require(:post).permit(
      :content,
      :send_user_id,
      :user_id,
      :category_id
    )
  
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, {only: [:index, :show, :edit, :update, :message]}
  before_action :forbid_login_user, {only: [:new, :create, :login_form, :login]}
  before_action :ensure_correct_user, {only: [:edit, :update]}
  
  def index
    @users = User.all
  end
  
  def show
    @user = User.find_by(id: params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(
      name: params[:name],
      email: params[:email],
      image_name: "default_user.jpg",
      password: params[:password]
    )
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "ユーザー登録が完了しました"
      redirect_to("/users/#{@user.id}")
    else
      render("users/new")
    end
  end
  
  def edit
    @user = User.find_by(id: params[:id])
  end
  
  def update
    @user = User.find_by(id: params[:id])
    @user.name = params[:name]
    @user.email = params[:email]
    @user.introduction = params[:introduction]
    
    if params[:image]
      @user.image_name = "#{@user.id}.jpg"
      image = params[:image]
      File.binwrite("public/user_images/#{@user.image_name}", image.read)
    end
    
    if @user.save
      flash[:notice] = "ユーザー情報を編集しました"
      redirect_to("/users/#{@user.id}")
    else
      render("users/edit")
    end
  end
  
  def login_form
  end
  
  def login
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "ログインしました"
      redirect_to("/posts/index")
    else
      @error_message = "メールアドレスまたはパスワードが間違っています"
      @email = params[:email]
      @password = params[:password]
      render("users/login_form")
    end
  end
  
  def logout
    session[:user_id] = nil
    flash[:notice] = "ログアウトしました"
    redirect_to("/login")
  end
  
  def likes
    @user = User.find_by(id: params[:id])
    @likes = Like.where(user_id: @user.id)
  end
  
  def ensure_correct_user
    if @current_user.id != params[:id].to_i
      flash[:notice] = "権限がありません"
      redirect_to("/posts/index")
    end
  end
  
  def message
    @messages = Post.where(send_user_id: @current_user.id)
    @user = User.find_by(id: params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/category/select_category_index.html.erb
<div class="main posts-index">
  <div class="container">
    <div class="category_index">Thanks</div>
      <div class="posts-index-item">
        <div class="post-right">
          <% @select_category_index1.each do |select_category_index| %>
            <div class="category_index_item">
              <%= link_to(select_category_index.content, "/posts/category_id: 1") %>
            </div>
          <% end %>
        </div>
      </div>

    <div class="category_index">Surprise</div>
      <div class="posts-index-item">
        <div class="post-right">
          <% @select_category_index2.each do |select_category_index| %>
            <div class="category_index_item">
              <%= link_to(select_category_index.content, "/posts/category_id: 2") %>
            </div>
          <% end %>
        </div>
      </div>

    <div class="category_index">Laugh</div>
      <div class="posts-index-item">
        <div class="post-right">
          <% @select_category_index3.each do |select_category_index| %>
            <div class="category_index_item">
              <%= link_to(select_category_index.content, "/posts/category_id: 3") %>
            </div>
          <% end %>
        </div>
      </div>       

    <div class="category_index">Impression</div>
      <div class="posts-index-item">
        <div class="post-right">
          <% @select_category_index4.each do |select_category_index| %>
            <div class="category_index_item">
              <%= link_to(select_category_index.content, "/posts/category_id: 4") %>
            </div>
          <% end %>
        </div>
      </div>  
  </div>
</div>

app/views/home/about.html.erb
<div class="about-main">
  <h2>ThanksAppとは...</h2>
  <p>
    日常で伝えにくい感謝を投稿するアプリです。<br>
    送り先に他のユーザーを選んでメッセージを送り、感謝の気持ちをみんなで共有することができます。<br>
    他にも、「驚き」「笑い」「感動」など様々な気持ちを発信して周りの人に笑顔を届けましょう！
  </p>
</div>

app/views/home/top.html.erb
<div class="about-main">
    <div class="top-message">
        <h2>「ありがとう」<br>伝えそびれていませんか？</h2>
        <p>周りの人への感謝の気持ちをみんなに発信しましょう！</p>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThanksApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  
  </head>

  <body>
    <header>
      <div class="header-logo">
        <% if @current_user %>
          <%= link_to("ThanksApp", "/posts/index") %>
        <% else %>
          <%= link_to("ThanksApp", "/") %>
        <% end %>
      </div>
      <ul class="header-menus">
        <% if @current_user %>
          <li>
            <%= link_to(@current_user.name, "/users/#{@current_user.id}") %>
          </li>
          <li>
            <%= link_to("カテゴリー", "/category/select_category_index") %>
          </li>
          <li>
            <%= link_to("投稿一覧", "/posts/index") %>
          </li>
          <li>
            <%= link_to("新規投稿", "/posts/new") %>
          </li>
          <li>
            <%= link_to("ユーザー一覧", "/users/index") %>
          </li>
          <li>
            <%= link_to("ログアウト", "/logout", {method: :post}) %>
          </li>
        <% else %>
          <li>
            <%= link_to("ThanksAppとは", "/about") %>
          </li>
          <li>
            <%= link_to("新規登録", "/signup") %>
          </li>
          <li>
            <%= link_to("ログイン", "/login") %>
          </li>
        <% end %>
      </ul>
    </header>

    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="main posts-index">
  <div class="container">
    <h1 class="users-heading">投稿一覧</h1>
    <% @posts.each do |post| %>
      <div class="posts-index-item">
        <div class="post-left">
          <img src="<%="/user_images/#{post.user.image_name}"%>">
        </div>
        <div class="post-right">
          <div class="post-user-name">
            <%= link_to(post.user.name, "/users/#{post.user.id}") %>
          </div>
          <p>category:<%=link_to(post.category.name,"/posts/#{post.id}")%></p>
          <p>to:<%=link_to(post.send_user.name,"/posts/#{post.id}")%></p>
          <%=link_to(post.content,"/posts/#{post.id}")%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="main posts-new">
  <div class="container">
    <h1 class="form-heading">メッセージを投稿する</h1>
      <div class="form">
        <div class="form-body">
          <% @post.errors.full_messages.each do |message| %>
            <div class="form-error">
              <%= message %>
            </div>
          <% end %>

          <%= form_with model: @post, url: posts_create_path do |f| %>
            <%= f.collection_select :category_id, Category.all, :id, :name, include_blank: "カテゴリーを選択して下さい" %>
            <%= f.collection_select :send_user_id, User.where.not(id: @current_user.id), :id, :name, include_blank: "送る相手を選択して下さい" %>
            <%= f.hidden_field :user_id, value: @current_user.id %>
            <%= f.text_area :content, size: "20x10" %>
            <%= f.submit "投稿" %>
          
          <% end %>
        </div>
      </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="main posts-show">
  <div class="container">
    <div class="posts-show-item">
      <div class="post-user-name">
        <img src="<%= "/user_images/#{@user.image_name}" %>">
        <%= link_to(@user.name,"users/#{@user.id}") %>
      </div>

      <p>
        category:<%= @post.category.name %>
      </p>

      <p>
        to:<%= @post.send_user.name %>
      </p>

      <p>
        <%= @post.content %>
      </p>

      <div class="post-time">
        <%= @post.created_at %>
      </div>
      
    <% if Like.find_by(user_id: @current_user.id, post_id: @post.id) %>
      <%= link_to("/likes/#{@post.id}/destroy", {method: "post"}) do%>
        <span class="fa fa-heart like-btn-unlike"></span>
      <% end %>
    <% else %>
      <%= link_to("/likes/#{@post.id}/create", {method: "post"}) do%>
        <span class="fa fa-heart like-btn"></span>
      <% end %>
    <% end %>
    <%= @likes_count %>

      <div class="post-menus">
        <% if @post.user_id == @current_user.id %>
          <%= link_to("編集", "/posts/#{@post.id}/edit") %>
          <%= link_to("削除", "/posts/#{@post.id}/destroy", {method: "post"}) %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="main users-edit">
  <div class="container">
    <div class="form-heading">ユーザー情報の編集</div>
    <div class="form users-form">
      <div class="form-body">
        <% @user.errors.full_messages.each do |message| %>
          <div class="form-error">
            <%= message %>
          </div>
        <% end %>
        <%= form_tag("/users/#{@user.id}/update", {multipart: true}) do %>
          <p>ユーザー名</p>
          <input name="name" value="<%=@user.name%>">
          <p>画像</p>
          <input name="image" type="file">
          <p>メールアドレス</p>
          <input name="email" value="<%=@user.email%>">
          <p>プロフィール</p>
          <textarea type="introduction" name="introduction" value="<%= @user.introduction %>"></textarea>
          <input type="submit" value="保存">
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="main users-index">
  <div class="container">
    <h1 class="users-heading">ユーザー一覧</h1>
    <% @users.each do |user| %>
      <div class="users-index-item">
        <div class="user-left">
          <img src="<%= "/user_images/#{user.image_name}" %>">
        </div>
        <div class="user-right">
          <%= link_to(user.name, "/users/#{user.id}") %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/likes.html.erb
<div class="main user-show">
  <div class="container">
    <div class="user">
      <img src="<%= "/user_images/#{@user.image_name}" %>">
      <h2><%= @user.name %></h2>
      <p><%= @user.introduction %></p>
      <% if @user.id == @current_user.id %>
        <%= link_to("プロフィールを編集", "/users/#{@user.id}/edit") %>
      <% end %>
    </div>
    
    <ul class="user-tabs">
      <li class="active"><%= link_to("投稿", "/users/#{@user.id}") %></li>
      <li class="active"><%= link_to("いいね!", "/users/#{@user.id}/likes") %></li>
      <li class="active"><%= link_to("届いたメッセージ", "/users/#{@user.id}/message") %></li>
    </ul>
    
    <% @likes.each do |like| %>
      <% post=Post.find_by(id: like.post_id) %>
      
      <div class="posts-index-item">
        <div class="post-left">
          <img src="<%= "/user_images/#{post.user.image_name}" %>">
        </div>
        <div class="post-right">
          <div class="post-user-name">
            <%= link_to(post.user.name, "/users/#{post.user.id}") %>
          </div>
          <p>category:<%= link_to(post.category.name, "/posts/#{post.id}") %></p>
          <p>to:<%= link_to(post.send_user.name, "/posts/#{post.id}") %></p>
          <%= link_to(post.content, "/posts/#{post.id}") %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/login_form.html.erb
<div class="main users-new">
  <div class="container">
    <div class="form-heading">ログイン</div>
    <div class="form users-form">
      <div class="form-body">
        <% if @error_message %>
          <div class="form-error">
            <%= @error_message %>
          </div>
        <% end %>
        <%=form_tag("/login") do %>
          <p>メールアドレス</p>
          <input name="email">
          <p>パスワード</p>
          <input name="password" type="password">
          <input type="submit" value="ログイン">
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/message.html.erb
<div class="main user-show">
　<div class="container">
    <div class="user">
      <img src="<%= "/user_images/#{@user.image_name}" %>">
      <h2><%= @user.name %></h2>
      <p><%= @user.introduction %></p>
      <% if @user.id == @current_user.id %>
        <%= link_to("プロフィールを編集", "/users/#{@user.id}/edit") %>
      <% end %>
    </div>
    
    <ul class="user-tabs">
        <li class="active"><%= link_to("投稿", "/users/#{@user.id}") %></li>
        <li class="active"><%= link_to("いいね!", "/users/#{@user.id}/likes") %></li>
        <li class="active"><%= link_to("届いたメッセージ", "/users/#{@user.id}/message") %></li>
    </ul>
    
    <% @messages.each do |message| %>
      <div class="posts-index-item">
        <div class="post-left">
          <img src="<%= "/user_images/#{message.user.image_name}" %>">
        </div>
        <div class="post-right">
          <div class="post-user-name">
            <%= link_to(message.user.name, "/users/#{message.user.id}") %>
          </div>
          <p>category:<%= link_to(message.category.name, "/posts/#{message.id}") %></p>
          <p>to:<%= link_to(message.send_user.name, "/posts/#{message.id}") %></p>
          <%= link_to(message.content, "/posts/#{message.id}") %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="main users-new">
  <div class="container">
    <div class="form-heading">新規ユーザー登録</div>
      <div class="form users-form">
        <div class="form-body">
          <% @user.errors.full_messages.each do |message| %>
            <div class="form-error">
              <%= message %>
            </div>
          <% end %>

          <%= form_tag("/users/create") do %>
            <p>ユーザー名</p>
            <input name="name" value="<%= @user.name %>">
        
            <p>メールアドレス</p>
            <input name="email" value="<%= @user.email %>">
        
            <p>パスワード</p>
            <input type="password" name="password" value="<%= @user.password %>">
            
            <p>プロフィール</p>
            <textarea type="introduction" name="introduction" value="<%= @user.introduction %>"></textarea>

            <br>
            <input type="submit" value="新規登録">
          <%end%>
        </div>  
      </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="main user-show">
  <div class="container">
    <div class="user">
      <img src="<%= "/user_images/#{@user.image_name}" %>">
      <h2><%= @user.name %></h2>
      <p><%= @user.email %></p>
      <p><%= @user.introduction %></p>
      <% if @user.id == @current_user.id %>
        <%= link_to("編集", "/users/#{@user.id}/edit") %>
      <% end %>
    </div>
    
    <% @user.posts.each do |post| %>
      <div class="posts-index-item">
        <div class="post-left">
          <img src="<%= "/user_images/#{post.user.image_name}" %>">
        </div>
        <div class="post-right">
          <div class="post-user-name">
            <%= link_to(post.user.name, "/users/#{post.user.id}") %>
          </div>
          <%= link_to(post.content, "/posts/#{post.id}") %>
        </div>
      </div>
    <% end %>
  </div>
</div>